source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'HPAOPSignal_Example' do
  pod 'HPAOPSignal', :path => '../'
  pod 'Aspects'

  target 'HPAOPSignal_Tests' do
    inherit! :search_paths

    
  end
end
